version: ‘3’
services: 
   onchain:
      container_name: onchainmanager
      build:
         context: .
         dockerfile: docker/on-chain/Dockerfile 
      ports:
         - 8545:8545

   shard1:
      container_name: shard1
      build:
         context: .
         dockerfile: docker/docker-ganache1/Dockerfile
      ports:
         - 8546:8546

   shard2:
      container_name: shard2
      build:
         context: .
         dockerfile: docker/docker-ganache2/Dockerfile
      ports:
         - 8547:8547

   shard3:
      container_name: shard3
      build:
         context: .
         dockerfile: docker/docker-ganache3/Dockerfile
      ports:
         - 8548:8548

   shard4:
      container_name: shard4
      build:
         context: .
         dockerfile: docker/docker-ganache4/Dockerfile
      ports:
         - 8549:8549

   shard5:
      container_name: shard5
      build:
         context: .
         dockerfile: docker/docker-ganache5/Dockerfile
      ports:
         - 8550:8550

   shard6:
      container_name: shard6
      build:
         context: .
         dockerfile: docker/docker-ganache6/Dockerfile
      ports:
         - 8551:8551

   shard7:
      container_name: shard7
      build:
         context: .
         dockerfile: docker/docker-ganache7/Dockerfile
      ports:
         - 8552:8552

   shard8:
      container_name: shard8
      build:
         context: .
         dockerfile: docker/docker-ganache8/Dockerfile
      ports:
         - 8553:8553

